# Generated by Django 3.2.5 on 2022-06-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quiz_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizzes'},
        ),
    ]
