# Generated by Django 3.2.5 on 2022-06-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20220618_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
