# Generated by Django 3.2.5 on 2022-05-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_auto_20220522_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Birth Year'),
        ),
        migrations.AddField(
            model_name='user',
            name='city_state',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City/State'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.IntegerField(blank=True, null=True, verbose_name='Experience'),
        ),
    ]
