name: 🚀 Deploy to Production

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Unset Git Proxy
        run: |
          unset GIT_PROXY_COMMAND

      - name: Debug Environment
        run: |
          pwd
          ls -la
          cd api
          ls -la
          source venv/bin/activate
          which python
          python --version

      - name: Upload
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          use_insecure_cipher: true
          script: |
            cd api
            source venv/bin/activate
            git pull
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            python manage.py migrate
            sudo systemctl restart gunicorn
          timeout: 30s
          command_timeout: 10m
          proxy_port: 22
          proxy_timeout: 30s
